### ISSUE TITLE
feat: option to allow duplicate words

### ISSUE THREAD

**Issue by adamdecaf** [Abirdcfly/dupword#26]
Is there an option for allowing some duplicate words without an annotation? My example is hex characters that aren't actually repeated.  This example comes from [moov-io/dukpt](https://github.com/moov-io/dukpt/actions/runs/6125362043/job/16627184327).

```
pkg/des/des_internal.go:116:2: Duplicate words (C0C0) found (dupword)
	// 4) XOR the Key Register with hexadecimal "C0C0 C0C0 0000 0000 C0C0 C0C0 0000 0000"
	^
```

I've tried to double quote the hex characters, but that doesn't seem to help.

**Comment by Abirdcfly** [comment]
Thank you for your advice!. I plan to work on implementing this feature this week.
